/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package source.OtherUtilityForms;

import java.awt.Window;
import java.io.File;
import java.io.PrintWriter;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import source.DatabaseTools;
import source.Main;
import static source.OtherUtilityForms.DataEntry.folder;

/**
 *
 * @author anze
 */
public class ExportLog extends javax.swing.JPanel {

    DatabaseTools dbt = new DatabaseTools();
    static String path = new File("data" + File.separator + "jLogQSL_export.adi").getAbsolutePath();

    /**
     * Creates new form ExportLog
     */
    public ExportLog() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jOptionPane1 = new javax.swing.JOptionPane();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 51, 51));
        jLabel5.setText("*");

        setToolTipText("Export log");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Choose export format:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ADIF (.adi)", "ADIF (.log)", "CSV (.csv)", "TXT (.txt)", "PDF (.pdf)" }));
        jComboBox1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jComboBox1FocusGained(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Choose export path:");

        jButton1.setForeground(new java.awt.Color(102, 204, 255));
        jButton1.setText("Choose");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 51, 51));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("*");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 51, 51));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("*");

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 204, 0));
        jButton2.setText("Export");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 51, 51));
        jButton3.setText("Cancel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel3.setText("Current path:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel6))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel7))))
                            .addComponent(jLabel3))
                        .addGap(0, 191, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jButton1)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String sql_call = "SELECT L.ID AS ID, L.callsign AS CALLSIGN, L.date AS 'DATE & TIME', L.sent_report AS 'SENT REPORT', L.received_report AS 'RECEIVED REPORT', "
                + "B.name AS BAND, M.name AS MODE, L.power AS POWER, L.frequency AS FREQUENCY, L.qth AS QTH, Q.name AS 'MY QTH', L.note AS NOTE "
                + "FROM log_entries L "
                + "LEFT JOIN modes M ON M.id = L.modes_id "
                + "LEFT JOIN BANDS B ON B.id = L.bands_id "
                + "LEFT JOIN custom_qths Q ON Q.id = L.custom_qths_id";
        String[][] data = dbt.getArrayFromQuery(Main.DBpathPublic, sql_call, jOptionPane1);
        try {
            switch (jComboBox1.getSelectedIndex()) {
                case 0:
                    // ADIF (.adi)
                    break;
                case 1:
                    //ADIF (.log)
                    break;
                case 2:
                    //CSV (.csv)
                    PrintWriter pw = new PrintWriter(new File(path));
                    for (int i = 0; i < data.length; i++) {
                        writeStringOrInt(pw, data[i][0], true);
                        for (int j = 1; j < data[i].length; j++) {
                            writeStringOrInt(pw, data[i][j], false);
                        }
                        pw.print("\n");
                    }
                    pw.close();
                    break;
                case 3:
                    //TXT (.txt)
                    break;
                case 4:
                    //PDF (.pdf)
                    break;
            }
        } catch (Exception e) {
            jOptionPane1.showMessageDialog(null, "Failed to write data.", "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Window this_w = SwingUtilities.getWindowAncestor(this);
        if (this_w != null) {
            this_w.dispose();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFileChooser picker = new JFileChooser();
        picker.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int result = picker.showOpenDialog(null);

        if (result == JFileChooser.APPROVE_OPTION) {
            folder = picker.getSelectedFile();
            path = folder.toString() + File.separator + "jLogQSL_export" + jComboBox1.getSelectedItem().toString().split("[()]")[1]; //Get the 2nd item of the array cuz i split per '('  
            jLabel3.setText("Current path: " + path);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        switch (jComboBox1.getSelectedIndex()) {
            case 0:
                // ADIF (.adi)
                changeFileExtention("adi");
                break;
            case 1:
                //ADIF (.log)
                changeFileExtention("log");
                break;
            case 2:
                //CSV (.csv)
                changeFileExtention("csv");
                break;
            case 3:
                //TXT (.txt)
                changeFileExtention("txt");
                break;
            case 4:
                //PDF (.pdf)
                changeFileExtention("pdf");
                break;
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBox1FocusGained
        jLabel3.setText("Current path: " + path);
    }//GEN-LAST:event_jComboBox1FocusGained

    public void changeFileExtention(String newExtension) {
        String tmp[] = path.split("\\.");
        tmp[tmp.length - 1] = newExtension;
        path = String.join(".", tmp);
        jLabel3.setText("Current path: " + path);
    }

    public void writeStringOrInt(PrintWriter pw, String attribute, boolean isFirst) {
        if (attribute == null || attribute.isEmpty()) {
            if (!isFirst) {
                pw.print(",");
            }
            return;
        }
        try {
            int tmp = Integer.parseInt(attribute);
            if (isFirst) {
                pw.print(tmp);
            } else {
                pw.print("," + tmp);
            }
            return;
        } catch (NumberFormatException e) {
            // if not int, try double
        }

        try {
            double tmp = Double.parseDouble(attribute);
            if (isFirst) {
                pw.print(tmp);
            } else {
                pw.print("," + tmp);
            }
        } catch (NumberFormatException e) {
            if (isFirst) {
                pw.print("\"" + attribute.replace("\"", "\"\"").replace("\n", " ") + "\"");
            } else {
                pw.print(",\"" + attribute.replace("\"", "\"\"").replace("\n", " ") + "\"");
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JOptionPane jOptionPane1;
    // End of variables declaration//GEN-END:variables
}
